# Generated by Django 3.1.7 on 2021-03-09 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.CharField(max_length=30)),
                ('contact_summary', models.CharField(max_length=50)),
                ('contact_message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('user_edit', models.SlugField(max_length=1000)),
                ('bio', models.TextField(max_length=120)),
                ('member', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
